export const USER_ACTION_TYPE = {
    SET_CURRENT_USER: 'user/SET_CURRENT_USER',
    CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',
    
    GOOGLE_SING_IN_START: 'user/GOOGLE_SING_IN_START',
    EMAIL_SING_IN_START: 'user/EMAIL_SING_IN_START',
    SING_IN_SUCCESS: 'user/SING_IN_SUCCESS',
    SING_IN_FAILD: 'user/SING_IN_FAILD',

    SIGN_UP_START: 'user/SIGN_UP_START',
    SIGN_UP_SUCCESS: 'user/SIGN_UP_SUCCESS',
    SIGN_UP_FAILD: 'user/SIGN_UP_FAILD',
}